# Generated by Django 4.2.16 on 2024-12-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_user_username_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='competition',
            name='voting_type',
            field=models.CharField(choices=[('single_choice', 'Одиночный выбор'), ('multiple_choice', 'Множественный выбор')], default='single_choice', max_length=50),
        ),
    ]
