# Generated by Django 4.2.16 on 2024-12-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_competition_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен для участия'), ('voting', 'Идёт голосование'), ('completed', 'Завершён')], default='available', max_length=20),
        ),
    ]
