# Generated by Django 4.2.16 on 2024-12-04 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_competition_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
